// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxUxGvTLcx7wWhryYHuKAMoX8Jb3A-ssM',
    appId: '1:976257565610:web:5952b2bc5d48a68efa61d3',
    messagingSenderId: '976257565610',
    projectId: 'locatewiki2324',
    authDomain: 'locatewiki2324.firebaseapp.com',
    storageBucket: 'locatewiki2324.appspot.com',
    measurementId: 'G-ZBS8VRH55E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACUZ0r2HYhyMvvmZKKOJVz0RHJLnWhT6k',
    appId: '1:976257565610:android:4729df07713bac72fa61d3',
    messagingSenderId: '976257565610',
    projectId: 'locatewiki2324',
    storageBucket: 'locatewiki2324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGh__TLAvW5f_VPBySiqiBkZCMjpylW4s',
    appId: '1:976257565610:ios:5dd4a0f4eb24b131fa61d3',
    messagingSenderId: '976257565610',
    projectId: 'locatewiki2324',
    storageBucket: 'locatewiki2324.appspot.com',
    iosBundleId: 'com.example.locatewikiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGh__TLAvW5f_VPBySiqiBkZCMjpylW4s',
    appId: '1:976257565610:ios:914e7e8289ec7ba3fa61d3',
    messagingSenderId: '976257565610',
    projectId: 'locatewiki2324',
    storageBucket: 'locatewiki2324.appspot.com',
    iosBundleId: 'com.example.locatewikiFlutter.RunnerTests',
  );
}
